---
- name: Add cluster hosts to local /etc/hosts
  sudo: yes
  action: lineinfile
          state=present
          dest=/etc/hosts
          line="{{ hostvars[item]['ansible_ssh_host'] }} {{ item }}"
  when: hostvars[item]['ansible_ssh_host'] is defined
  with_items: groups.all
  