---
- name: install nfs server
  action: yum pkg=nfs-utils state=present
  tags:
    - nfs

- name: install nfs client
  action: yum pkg=nfs-utils state=present
  tags:
    -nfs

# CentOS 6 does not start needed services after installation
- name: ensure nfs service is running (CentOS)
  action: service name="{{ item }}" state=started
  tags:
    - nfs
  with_items:
    - rpcbind
    - nfslock
    - nfs
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == 6

