---
- name: Update, bootstrap and reboot if necessary
  hosts: all
  sudo: yes
  tasks:
  - name: stop cloud-init managing /etc/hosts
    action: "lineinfile dest=/etc/cloud/cloud.cfg.d/10_etc_hosts.cfg state=present regexp='^manage_etc_hosts' line='manage_etc_hosts: False'"

  - name: fix /etc/hosts after cloud-init
    lineinfile: dest=/etc/hosts state=absent regexp="{{ inventory_hostname }}"

  - name: clean yum state (CentOS)
    action: shell yum clean all
    when: is_centos

  - name: update packages (CentOS)
    yum: name=* state=latest
    when: is_centos

  - name: disable SELinux (CentOS)
    action: selinux state=disabled
    when: is_centos

  - name: reboot (CentOS)
    action: shell reboot
    when: is_centos

