---
- name: Update, bootstrap and reboot
  hosts: all
  sudo: yes
  tasks:
  - name: stop cloud-init managing /etc/hosts
    action: "lineinfile dest=/etc/cloud/cloud.cfg.d/10_etc_hosts.cfg state=present regexp='^manage_etc_hosts' line='manage_etc_hosts: False'"

  - name: fix /etc/hosts after cloud-init
    lineinfile: dest=/etc/hosts state=absent regexp="{{ inventory_hostname }}"

  - name: clean yum state
    action: shell yum clean all

  - name: update packages
    yum: name=* state=latest

  - name: disable SELinux on CentOS
    action: selinux state=disabled
    when: ansible_distribution == 'CentOS'

  - name: reboot
    action: shell reboot
