- name: Ensure spark local directory exists
  file: path="{{ item }}" state=directory owner=root mode=1777
  with_items:
    - "{{ spark_localdir }}"
  
- name: configure slaves file
  template: src=spark/templates/slaves.j2 dest="{{ spark_confdir }}/slaves" owner=root mode=0644
  when: inventory_hostname in groups.hadoop_namenode

- name: copy spark-env.sh 
  template: dest="{{ spark_confdir }}/spark-env.sh" src=spark/templates/spark-env.sh.j2 owner=root group=root mode=0755
  
