- name: Ensure spark local directory exists
  file: path="{{ item }}" state=directory owner=root mode=1777
  with_items:
    - "{{ spark_localdir }}"
  
- name: configure slaves file
  action: template src=spark/templates/slaves.j2 dest="{{ spark_confdir }}/slaves" owner=root mode=0644
  when: inventory_hostname in groups.hadoop_namenode

- name: copy spark-env.sh 
  action: template dest="{{ spark_confdir }}/spark-env.sh" src=spark/files/spark-env.sh owner=root group=root mode=0755

- name: copy spark-defaults.conf
  action: template dest="{{ spark_confdir }}/spark-defaults.conf" src=spark/files/spark-defaults.conf owner=root group=root mode=0755

- name: copy core-site.xml
  action: template dest="{{ spark_confdir }}/core-site.xml" src=spark/files/core-site.xml owner=root group=root mode=0755

- name: Ensure spark-jars directory exists
  file: path="{{ spark_sparkjarsdir }}" state=directory owner=root mode=0755

- name: copy hadoop-openstack driver
  copy: dest="{{ spark_sparkjarsdir }}/hadoop-openstack-3.0.0-SNAPSHOT.jar" src=spark/files/hadoop-openstack-3.0.0-SNAPSHOT.jar owner=root group=root mode=0755  
