---
- name: install dependencies
  yum: pkg="{{ item }}" state=present
  with_items:
    - java-openjdk
  when: is_centos

- name: install dependencies
  apt: pkg="{{ item }}" state=installed update_cache=yes
  with_items:
    - default-jdk
  when: is_debian_or_ubuntu

- name: download Spark
  get_url: url="{{ tar_url }}" dest=/tmp/spark-{{ spark_version }}-bin-{{ spark_flavor }}.tar.gz

- name: extract Spark
  command: creates=/opt/spark-{{ spark_version }}-bin-{{ spark_flavor }} /bin/tar xfz /tmp/spark-{{ spark_version }}-bin-{{ spark_flavor }}.tar.gz -C /opt

- name: create a shortcut symlink to the extracted directory
  file: state=link src=/opt/spark-{{ spark_version }}-bin-{{ spark_flavor }} dest=/opt/spark
  
    