---
- name: Ensure all needed packages are installed (Ubuntu)
  when: is_debian_or_ubuntu
  apt: name="{{ item }}" state=installed
  with_items:
    - default-jdk
    - sudo
    - snappy
    - libsnappy-dev

- name: Ensure all needed packages are installed (CentOS)
  when: is_centos
  yum: name="{{ item }}" state=installed
  with_items:
    - java-openjdk
    - sudo
    - snappy
    - snappy-devel

- name: download and install hadoop debian package
  when: is_debian_or_ubuntu
  shell: dpkg -l hadoop | grep ^ii || (tmpfile=$(mktemp tmp.XXXXXXXXX.deb); wget {{ deburl }} -O $tmpfile -o /dev/null; dpkg -i $tmpfile; rc=$?; rm -f $tmpfile; exit $rc)


- name: download and install hadoop centos package
  when: is_centos
  action: shell rpm -q hadoop || yum install -y {{ rpmurl }}
