---
- name: Install ganglia monitor (Ubuntu)
  apt: name={{item}} state=latest
  with_items:
    - ganglia-monitor
  when: is_debian_or_ubuntu
  tags:
    - ganglia

- name: Install ganglia monitor (CentOS)
  yum: name={{item}} state=latest
  with_items:
    - ganglia-gmond
  when: is_centos
  tags:
    - ganglia

- name: Configure gmond
  template: src=ganglia/templates/gmond.conf.j2 dest=/etc/ganglia/gmond.conf
  notify:
    - restart ganglia-monitor
    - restart gmond
    - restart gmetad
  tags:
    - ganglia
    - gmond

- name: Ensure gmond is running and enabled (CentOS)
  service: name=gmond state=started enabled=true
  when: is_centos
  tags:
    - ganglia

- name: Ensure ganglia-monitor is running and enabled (Ubuntu)
  service: name=ganglia-monitor state=started enabled=true
  when: is_debian_or_ubuntu
  tags:
    - ganglia
